version: '3.8'

services:
  main: 
    container_name: nestJS
    image: node:14.18.0
    ports:
      - 5000:5000
      - 9229:9229      
    working_dir: /src/app
    volumes:
      - '.:/src/app'
      - './node_modules:/app/node_modules'
    command: yarn start:debug  
    environment:      
      HTTP_PORT: 5000 
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo1
    image: mongo    
    volumes:
      - /home/jazmin/mongodb/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_DATABASE=thedbname
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  mongood:
    container_name: mongo1-client
    links:
     - mongodb
    image: renzholy/mongood:latest    
    environment:
      - MONGO_URI=mongodb://root:root@127.0.0.1:27017/thedbname?authSource=admin
      
    ports:
      - "3001:3000"



  
     